<?php
declare(strict_types=1);

// AttackOnTitan SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

AttackOnTitanUtility::setRegistrar(function (AttackOnTitanUtility $u): void {
    $u->clean = [AttackOnTitanClean::class, 'call'];
    $u->done = [AttackOnTitanDone::class, 'call'];
    $u->make_error = [AttackOnTitanMakeError::class, 'call'];
    $u->feature_add = [AttackOnTitanFeatureAdd::class, 'call'];
    $u->feature_hook = [AttackOnTitanFeatureHook::class, 'call'];
    $u->feature_init = [AttackOnTitanFeatureInit::class, 'call'];
    $u->fetcher = [AttackOnTitanFetcher::class, 'call'];
    $u->make_fetch_def = [AttackOnTitanMakeFetchDef::class, 'call'];
    $u->make_context = [AttackOnTitanMakeContext::class, 'call'];
    $u->make_options = [AttackOnTitanMakeOptions::class, 'call'];
    $u->make_request = [AttackOnTitanMakeRequest::class, 'call'];
    $u->make_response = [AttackOnTitanMakeResponse::class, 'call'];
    $u->make_result = [AttackOnTitanMakeResult::class, 'call'];
    $u->make_point = [AttackOnTitanMakePoint::class, 'call'];
    $u->make_spec = [AttackOnTitanMakeSpec::class, 'call'];
    $u->make_url = [AttackOnTitanMakeUrl::class, 'call'];
    $u->param = [AttackOnTitanParam::class, 'call'];
    $u->prepare_auth = [AttackOnTitanPrepareAuth::class, 'call'];
    $u->prepare_body = [AttackOnTitanPrepareBody::class, 'call'];
    $u->prepare_headers = [AttackOnTitanPrepareHeaders::class, 'call'];
    $u->prepare_method = [AttackOnTitanPrepareMethod::class, 'call'];
    $u->prepare_params = [AttackOnTitanPrepareParams::class, 'call'];
    $u->prepare_path = [AttackOnTitanPreparePath::class, 'call'];
    $u->prepare_query = [AttackOnTitanPrepareQuery::class, 'call'];
    $u->graphql_body = [AttackOnTitanGraphql::class, 'body'];
    $u->graphql_errors = [AttackOnTitanGraphql::class, 'errors'];
    $u->result_basic = [AttackOnTitanResultBasic::class, 'call'];
    $u->result_body = [AttackOnTitanResultBody::class, 'call'];
    $u->result_headers = [AttackOnTitanResultHeaders::class, 'call'];
    $u->transform_request = [AttackOnTitanTransformRequest::class, 'call'];
    $u->transform_response = [AttackOnTitanTransformResponse::class, 'call'];
});
