// Command attack-on-titan-cli is a CLI + REPL for the AttackOnTitan SDK,
// built on the AQL engine. Positional args are joined into a single
// AQL expression and evaluated. With no args, falls into a REPL.
//
// Usage:
//
//   attack-on-titan-cli list <entity>
//   attack-on-titan-cli load <id> <entity>
//   attack-on-titan-cli                    # REPL
//
// Generated by sdkgen go-cli target. Do not edit by hand.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/aql-lang/aql/eng"
	"github.com/aql-lang/aql/eng/parser"
	sdk "github.com/voxgig-sdk/attack-on-titan-sdk/go"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	client := sdk.NewAttackOnTitanSDK(nil)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprint(out, "attack-on-titan> ")
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case ":quit", ":q", ":exit":
			return
		case ":help", ":h", ":?":
			fmt.Fprintln(out, "commands: list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities: character episode location organization titan")
			fmt.Fprintln(out, "meta:     :quit :help")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}

